---
- hosts: all
  become: true
  
  vars:
    mirror: mirror.deterlab.net

  tasks:
    - name: Setup resolv.conf
      lineinfile:
        dest: /etc/resolv.conf
        line: search vbed3.deterlab.net

    - name: Add stuff to testbed dns
      lineinfile:
        dest: /usr/local/etc/namedb/vbed3.deterlab.net.internal.db.head
        line: "{{ item }}"
      with_items:
        - "stem IN A 192.168.254.1"
        - "leaf IN A 192.168.254.2"

    - name: Re-initialize testbed dns
      command:  /usr/testbed/sbin/named_setup
    
    - name: Set up database
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/initdb.sql
    
    - name: Fetch Node Images
      get_url:
        url: "http://{{ mirror }}/deter/images/{{ item }}"
        dest: "/usr/testbed/images/{{ item }}"
      with_items:
        - Ubuntu1404-64-STD.ndz
        - Ubuntu1604-STD.ndz

    - name: Fetch Image Temp DBs
      get_url:
        url: "http://{{ mirror }}/deter/images/{{ item }}"
        dest: "/tmp/{{ item }}"
      with_items:
        - tempdb.sql
        - linux-mfs-tempdb.sql

    - name: Load image descriptors into DB
      command: perl /usr/testbed/obj/install/load-descriptors {{ item }}
      with_items:
        - /tmp/tempdb.sql
        - /tmp/linux-mfs-tempdb.sql

    - name: Add qnode type to DB
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/qnode.sql

    - name: Configrure mfs in DB
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/mfs.sql
    
    - name: Configrure mfs state transitions in DB
      mysql_db:
        state: import
        name: tbdb
        target: /tmp/config/mfs-state.sql

    - name: Create linux-mfs directory
      file:
        name: /usr/testbed/www/linux-mfs
        state: directory

    - name: Configure apache to serve linux-mfs
      copy:
        src: /tmp/config/mfs-htaccess
        dest: /usr/testbed/www/linux-mfs/.htaccess
        remote_src: true
    
    - name: Setup inetd + tftpd-hpa
      lineinfile:
        dest: /etc/inetd.conf
        line: "tftp dgram udp wait  root  /usr/libexec/tftpd  tftpd -l -s /tftpboot"

    - name: Create battlestar project
      command: su elabman -c "/tmp/config/first_project.sh"
    
    - name: restart inetd
      command: service inetd restart

    - name: Copy topomap to reloadpending
      copy:
        src: /tmp/config/topomap
        dest: /proj/emulab-ops/exp/reloadpending/tbdata/topomap
        remote_src: true

    - name: Tar reloadpending/topomap
      command: tar czf topomap.gz topomap
      args:
        chdir: /proj/emulab-ops/exp/reloadpending/tbdata
    
    - name: Copy topomap to reloading
      copy:
        src: /tmp/config/topomap
        dest: /proj/emulab-ops/exp/reloading/tbdata/topomap
        remote_src: true
    
    - name: Tar reloading/topomap
      command: tar czf topomap.gz topomap
      args:
        chdir: /proj/emulab-ops/exp/reloading/tbdata
    
    - name: Copy topomap to hwdown
      copy:
        src: /tmp/config/topomap
        dest: /proj/emulab-ops/exp/hwdown/tbdata/topomap
        remote_src: true
    
    - name: Tar hwdown/topomap
      command: tar czf topomap.gz topomap
      args:
        chdir: /proj/emulab-ops/exp/hwdown/tbdata

    - name: build lldp-switchmac
      shell: go build lldp-switchmac.go
      environment:
        GOPATH: /root/.go
      args:
        chdir: /opt/deter/switch-drivers/snmp/apps

    - name: install lldp-switchmac
      copy:
        src: /opt/deter/switch-drivers/snmp/apps/lldp-switchmac
        dest: /usr/testbed/sbin/lldp-switchmac
        mode: "a+x"
        remote_src: true
    
    - name: build dsnmp
      shell: go build snmp.go
      environment:
        GOPATH: /root/.go
      args:
        chdir: /opt/deter/switch-drivers/snmp/apps

    - name: install dsnmp
      copy:
        src: /opt/deter/switch-drivers/snmp/apps/snmp
        dest: /usr/testbed/bin/dsnmp
        mode: "a+x"
        remote_src: true
