---
- hosts: localhost
  become: true

  tasks:

    - name: fetch nodejs repo setup script
      get_url:
        url: https://deb.nodesource.com/setup_8.x
        dest: /tmp/nodesetup
        mode: "a+x"

    - name: install nodejs repo
      shell: /tmp/nodesetup

    - name: compute ubuntu libvirt package name
      set_fact:
        libvirtd_package: libvirt-bin
        libvirtd: libvirt-bin
      when: ansible_distribution == "Ubuntu"

    - name: compute debian libvirt package name
      set_fact:
        libvirtd_package: libvirt-daemon-system
        libvirtd: libvirtd
      when: ansible_distribution == "Debian"

    - name: install software
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - build-essential
        - redis-server
        - git
        - golang
        - libvirt-dev
        - "{{libvirtd_package}}"
        - nodejs
        - qemu-kvm
        - qemu-utils
        - nfs-kernel-server

    - name: set up filesystem
      file: path={{item.path}} state={{item.state}}
      with_items:
        - {path: /var/rvn/img, state: directory}
        - {path: /var/rvn/template, state: directory}
        - {path: /var/rvn/run, state: touch}
        - {path: /var/rvn/ssh, state: directory}
        - {path: /var/rvn/util, state: directory}
        - {path: /usr/local/lib/rvn, state: directory}
        - {path: /root/.ssh, state: directory}
        - {path: /root/.go, state: directory}
        - {path: /root/.go/src/github.com/rcgoodfellow, state: directory}

    - name: fetch base images
      get_url:
        url: http://mirror.deterlab.net/rvn/{{item}}
        dest: /var/rvn/img/{{item}}
      with_items:
        - cumulus-latest.qcow2
        - debian-stretch.qcow2
        - freebsd-11-router.qcow2
        - freebsd-11.qcow2

    - name: create netboot base image
      command: qemu-img create /var/rvn/img/netboot.qcow2 25G

    - name: install ssh keys
      get_url:
        url: http://mirror.deterlab.net/rvn/{{item}}
        dest: /var/rvn/ssh/{{item}}
      with_items:
        - rvn
        - rvn.pub
   
    #TODO untested
    - name: install text templates
      copy: src={{playbook_dir}}/rvn/{{item}} dest=/var/rvn/template/{{item}}
      with_items:
        - config.yml
        - sys.exports

    # ensure icmp from userspace applications works
    - lineinfile:
        dest: /etc/sysctl.conf
        line: net.ipv4.ping_group_range="0   2147483647"

    - command: sysctl -p
    #TODO end untested

    - name: install javascript libraries
      copy: src={{item.src}} dest=/usr/local/lib/rvn/{{item.dest}}
      with_items:
        - {src: run_model.js, dest: run_model.js}
        - {src: web/public/js/modeling.js, dest: modeling.js}

    - name: add raven keys to root
      copy: src=/var/rvn/ssh/{{item}} dest=/root/.ssh/{{item}} remote_src=true
      with_items:
        - rvn
        - rvn.pub

    - name: set private key permissions
      command: chmod 0600 /var/rvn/ssh/rvn

    - name: set up gopath
      lineinfile:
        dest: /root/.bashrc
        line: "{{item}}"
      with_items:
        - export GOPATH=/root/.go
        - PATH=$GOPATH/bin:$PATH

    - name: init runtime file
      shell: echo "{}" > /var/rvn/run

    - name: configure libvirt
      lineinfile:
        dest: /etc/libvirt/qemu.conf
        line: "{{item}}"
      with_items:
        - user = "root"
        - security_driver = "none"

    - name: restart libvirt
      service:
        name: "{{libvirtd}}"
        state: restarted

    - name: restart redis
      service:
        name: redis-server
        state: restarted

    - name: install go libraries
      shell: go get {{item}}
      environment:
        GOPATH: /root/.go
      with_items:
        - github.com/libvirt/libvirt-go
        - github.com/libvirt/libvirt-go-xml
        - github.com/revel/cmd/revel
        - github.com/go-redis/redis
        - github.com/sparrc/go-ping
        - github.com/fatih/color

    - name: link raven dir into gopath
      file:
        src: "{{playbook_dir}}"
        dest: /root/.go/src/github.com/rcgoodfellow/raven
        state: link
    
    - name: build utility programs
      shell: go build rvn.go
      args:
        chdir: /root/.go/src/github.com/rcgoodfellow/raven/rvn-cli
      environment:
        GOPATH: /root/.go
    
    - name: install rvn-cli
      copy:
        src: /root/.go/src/github.com/rcgoodfellow/raven/rvn-cli/rvn
        dest: /usr/local/bin/rvn
        remote_src: true
        mode: "a+x"

    - name: fetch utilities
      get_url:
        url: http://mirror.deterlab.net/rvn/util/{{item}}
        dest: /var/rvn/util/{{item}}
      with_items:
        - iamme-linux
        - iamme-freebsd

    - name: allow ping from go
      command: sysctl -w net.ipv4.ping_group_range="0   2147483647"
