---
- hosts: localhost
  become: true

  tasks:

    - name: fetch nodejs repo setup script
      get_url:
        url: https://deb.nodesource.com/setup_8.x
        dest: /tmp/nodesetup
        mode: "a+x"
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: install nodejs repo
      shell: /tmp/nodesetup
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: compute package names
      set_fact:
        devel_package: build-essential
        libvirtd_package: libvirt-daemon-system
        libvirtd: libvirtd
        redis_package: redis-server
        libvirt_dev_package: libvirt-dev
        qemu_utils_package: qemu-utils
        nfs_package: nfs-kernel-server
      when: ansible_distribution == "Debian"
      
    - name: compute package names
      set_fact:
        devel_package: build-essential
        libvirtd_package: libvirt-bin
        libvirtd: libvirt-bin
        redis_package: redis-server
        libvirt_dev_package: libvirt-dev
        qemu_utils_package: qemu-utils
        nfs_package: nfs-kernel-server
      when: ansible_distribution == "Ubuntu"
    
    - name: compute package names
      set_fact:
        libvirtd_package: libvirt-daemon-kvm
        libvirtd: libvirtd
        devel_package: "@development-tools"
        redis_package: redis
        libvirt_dev_package: libvirt-devel
        qemu_utils_package: qemu-common
        nfs_package: nfs-utils
      when: ansible_distribution == "Fedora"


    - name: install software
      package: name={{item}} state=latest
      with_items:
        - "{{devel_package}}"
        - "{{redis_package}}"
        - git
        - golang
        - "{{libvirtd_package}}"
        - "{{libvirt_dev_package}}"
        - nodejs
        - qemu-kvm
        - "{{qemu_utils_package}}"
        - "{{nfs_package}}"

    - name: link nodejs -> node
      file:
        src: '/usr/bin/node'
        dest: '/usr/bin/nodejs'
        state: link
      when: ansible_distribution == "Fedora"


    - name: set up filesystem
      file: path={{item.path}} state={{item.state}}
      with_items:
        - {path: /var/rvn/img, state: directory}
        - {path: /var/rvn/template, state: directory}
        - {path: /var/rvn/run, state: touch}
        - {path: /var/rvn/ssh, state: directory}
        - {path: /var/rvn/util, state: directory}
        - {path: /usr/local/lib/rvn, state: directory}
        - {path: /root/.ssh, state: directory}
        - {path: /root/.go, state: directory}
        - {path: /root/.go/src/github.com/rcgoodfellow, state: directory}

    - name: fetch base images
      get_url:
        url: http://mirror.deterlab.net/rvn/img/{{item}}
        dest: /var/rvn/img/{{item}}
      with_items:
        - cumulusvx-3.5.qcow2
        - debian-stretch.qcow2
        - fedora-27.qcow2
        - freebsd-11.qcow2
        - freebsd-11r.qcow2
        - freebsd-11d.qcow2

    - name: create netboot base image
      command: qemu-img create /var/rvn/img/netboot.qcow2 25G

    - name: install ssh keys
      get_url:
        url: http://mirror.deterlab.net/rvn/{{item}}
        dest: /var/rvn/ssh/{{item}}
      with_items:
        - rvn
        - rvn.pub
   
    #TODO untested
    - name: install text templates
      copy: src={{playbook_dir}}/rvn/{{item}} dest=/var/rvn/template/{{item}}
      with_items:
        - config.yml
        - sys.exports

    # ensure icmp from userspace applications works
    - lineinfile:
        dest: /etc/sysctl.conf
        line: net.ipv4.ping_group_range="0   2147483647"
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - lineinfile:
        dest: /etc/sysctl.conf
        line: net.ipv4.ping_group_range=0 1
      when: ansible_distribution == "Fedora"

    - command: sysctl -p
    #TODO end untested

    - name: install javascript libraries
      copy: src={{item.src}} dest=/usr/local/lib/rvn/{{item.dest}}
      with_items:
        - {src: run_model.js, dest: run_model.js}
        - {src: js/modeling.js, dest: modeling.js}

    - name: add raven keys to root
      copy: src=/var/rvn/ssh/{{item}} dest=/root/.ssh/{{item}} remote_src=true
      with_items:
        - rvn
        - rvn.pub

    - name: set private key permissions
      command: chmod 0600 /var/rvn/ssh/rvn

    - name: set up gopath
      lineinfile:
        dest: /root/.bashrc
        line: "{{item}}"
      with_items:
        - export GOPATH=/root/.go
        - PATH=$GOPATH/bin:$PATH

    - name: init runtime file
      shell: echo "{}" > /var/rvn/run

    - name: configure libvirt
      lineinfile:
        dest: /etc/libvirt/qemu.conf
        line: "{{item}}"
      with_items:
        - user = "root"
        - security_driver = "none"

    - name: restart libvirt
      service:
        name: "{{libvirtd}}"
        state: restarted

    - name: enable rpcbind
      service:
        name: rpcbind
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: restart rpcbind
      service:
        name: rpcbind
        state: restarted
      when: ansible_distribution == "Fedora"

    - name: enable nfs-server
      service:
        name: nfs-server
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: restart nfs-server
      service:
        name: nfs-server
        state: restarted
      when: ansible_distribution == "Fedora"


    - name: enable redis
      service:
        name: "{{redis_package}}"
        enabled: yes
      when: ansible_distribution == "Fedora"

    - name: restart redis
      service:
        name: "{{redis_package}}"
        state: restarted

    - name: install go libraries
      shell: go get {{item}}
      environment:
        GOPATH: /root/.go
      with_items:
        - github.com/libvirt/libvirt-go
        - github.com/libvirt/libvirt-go-xml
        - github.com/go-redis/redis
        - github.com/sparrc/go-ping
        - github.com/fatih/color

    - name: link raven dir into gopath
      file:
        src: "{{playbook_dir}}"
        dest: /root/.go/src/github.com/rcgoodfellow/raven
        state: link
    
    - name: build utility programs
      shell: go build rvn.go
      args:
        chdir: /root/.go/src/github.com/rcgoodfellow/raven/rvn-cli
      environment:
        GOPATH: /root/.go
    
    - name: install rvn-cli in /usr/local/bin
      copy:
        src: /root/.go/src/github.com/rcgoodfellow/raven/rvn-cli/rvn
        dest: /usr/local/bin/rvn
        remote_src: true
        mode: "a+x"

    - name: install rvn-cli in /usr/bin
      file:
        src: /usr/local/bin/rvn
        dest: /usr/bin/rvn
        state: link

    - name: fetch utilities
      get_url:
        url: http://mirror.deterlab.net/rvn/util/{{item}}
        dest: /var/rvn/util/{{item}}
      with_items:
        - iamme-linux
        - iamme-freebsd

    - name: allow ping from go
      command: sysctl -w net.ipv4.ping_group_range="0 1"
