---
- hosts: all
  become: true

  tasks:
    - name: set hostname
      hostname:
        name: {{.Host.Name}}

    - name: put hostname in /etc/hosts
      lineinfile:
        name: /etc/hosts
        line: '127.0.0.1    {{.Host.Name}}'

{{range .Host.Mounts}}
    - name: mount {{.Point}}
      mount:
        name: {{.Point}}
        src: {{$.NFS}}:{{.Source}}
        opts: soft
        fstype: nfs
        state: mounted
{{- end}}

