---
- hosts: all
  become: true

  tasks:

    - name: update apt-cache
      apt:
        update_cache: yes

    - apt: name={{item}} state=latest
      with_items:
        - vim
        - snmp
        - bash-completion

    - get_url:
        url: https://github.com/deter-project/switch-drivers/releases/download/v0.1/snmpd
        dest: /usr/local/bin/snmpd
        mode: "a+x"


