---
- hosts: all
  become: true

  tasks:

    - name: update apt-cache
      apt:
        update_cache: yes

    - apt: name={{item}} state=latest
      with_items:
        - vim
        - bash-completion

    - copy: src={{item.src}} dest={{item.dest}} remote_src=True
      with_items:
        - { src: '/tmp/config/interfaces', dest: '/etc/network/interfaces' }
        - { src: '/tmp/config/snmpd.conf', dest: '/etc/snmp/snmpd.conf' }
        - { src: '/tmp/config/lldpd.conf', dest: '/etc/lldpd.d/lldpd.conf' }
        - { src: '/tmp/config/lldpd_default', dest: '/etc/default/lldpd' }

    - file:
        path: /root/.go/src/github.com/rcgoodfellow
        state: directory

    - service:
        name: snmpd
        state: restarted

    - get_url:
        url: https://github.com/rcgoodfellow/agx/releases/download/v0.1/qbridge
        dest: /usr/local/bin/qbridge
        mode: "a+x"

    - shell: "{{item}}"
      with_items:
        # set up the bridge
        - ip link set down dev bridge | sleep 0
        - brctl delbr bridge | sleep 0
        - brctl addbr bridge
        - ip link set bridge type bridge vlan_filtering 1

        # add interfaces to the bridge
        - brctl addif bridge swp1
        - brctl addif bridge swp2
        - brctl addif bridge swp3
        - brctl addif bridge swp4

        # bring up the interfaces
        - ip link set up dev swp1
        - ip link set up dev swp2
        - ip link set up dev swp3
        - ip link set up dev swp4
        - ip link set up dev bridge

        # linux puts vid 1 on bridged interfaces by default, we don't want that
        - bridge vlan del vid 1 dev swp1
        - bridge vlan del vid 1 dev swp2
        - bridge vlan del vid 1 dev swp3
        - bridge vlan del vid 1 dev swp4

    - shell: nohup /usr/local/bin/qbridge > /dev/null 2>&1  &

