---
- hosts: all
  become: true

  tasks:

    - name: update apt-cache
      apt:
        update_cache: yes

    - name: install software
      apt: name={{item}} state=latest
      with_items:
        - lldpd
        - redis-server
        - python3-pip
        - ansible
        - sshpass
        - bash-completion
        - git
        - vim
        - tmux
        - golang
    
    - name: Set redis listening address
      lineinfile:
        name: /etc/redis/redis.conf
        regexp: "^bind *"
        line: "bind 0.0.0.0"

    - name: Restart redis
      command: service redis restart

    - name: Install redis-python
      command: pip3 install redis

    - file:
        path: /home/rvn/.go/src/github.com/rcgoodfellow
        state: directory
        owner: rvn
        group: rvn

    - file:
        src: /opt/walrus
        dest: /home/rvn/.go/src/github.com/rcgoodfellow/walrustf
        state: link
        owner: rvn
        group: rvn
    
    - lineinfile:
        line: "{{ item }}"
        path: /home/rvn/.bashrc
      with_items:
        - export GOPATH=/home/rvn/.go
        - export PATH=/home/rvn/.go/bin:$PATH
    
    - shell: go get {{item}}
      environment:
        GOPATH: /home/rvn/.go
      with_items:
        - github.com/fatih/color
        - github.com/go-redis/redis

    - shell: go install
      args:
        chdir: /home/rvn/.go/src/github.com/rcgoodfellow/walrustf/wtf
      environment:
        GOPATH: /home/rvn/.go
        GOBIN: /home/rvn/.go/bin
    
    - blockinfile:
        path: /etc/ansible/hosts
        content: |
          [nodes]
            n0 ansible_ssh_user=rvn ansible_ssh_pass=rvn
            n1 ansible_ssh_user=rvn ansible_ssh_pass=rvn
            nimbus ansible_ssh_user=rvn ansible_ssh_pass=rvn
            control ansible_ssh_user=rvn ansible_ssh_pass=rvn

    - blockinfile:
        path: /etc/ansible/ansible.cfg
        content: |
          [defaults]
          host_key_checking = False

    - file:
        path: /usr/share/bash-completion/completions/wtf
        state: absent
