---
- hosts: all
  become: true

  tasks:

    - name: update apt-cache
      apt:
        update_cache: yes

    - name: install software
      apt: name={{item}} state=latest
      with_items:
        - lldpd
        - redis-server
        - python3-pip
        - ansible
        - sshpass
        - bash-completion
        - git
        - vim
        - tmux
    
    - name: Set redis listening address
      lineinfile:
        name: /etc/redis/redis.conf
        regexp: "^bind *"
        line: "bind 0.0.0.0"

    - name: Restart redis
      command: service redis restart

    - name: Install redis-python
      command: pip3 install redis


    
    - get_url:
        url: https://github.com/rcgoodfellow/walrustf/releases/download/v0.1/wtf
        dest: /usr/local/bin/wtf
        mode: "a+x"

    - blockinfile:
        path: /etc/ansible/hosts
        content: |
          [nodes]
            n0 ansible_ssh_user=rvn ansible_ssh_pass=rvn
            n1 ansible_ssh_user=rvn ansible_ssh_pass=rvn
            nimbus ansible_ssh_user=rvn ansible_ssh_pass=rvn
            control ansible_ssh_user=rvn ansible_ssh_pass=rvn

    - blockinfile:
        path: /etc/ansible/ansible.cfg
        content: |
          [defaults]
          host_key_checking = False

    - file:
        path: /usr/share/bash-completion/completions/wtf
        state: absent
