---

- hosts: n0

  tasks:
    - name: clear existing pingtests
      command: pkill -f pingtest -9
      ignore_errors: yes
      tags:
        - vpath-create

    - name: ping test
      shell: /tmp/config/pingtest.sh 10.47.0.2 vpath-create >> /tmp/pingtest
      async: 3600
      poll: 0
      tags:
        - vpath-create

- hosts: n1

  tasks:
    - name: clear existing pingtests
      command: pkill -f pingtest -9
      ignore_errors: yes
      tags:
        - vpath-create

    - name: ping test
      shell: /tmp/config/pingtest.sh 10.47.0.1 vpath-create >> /tmp/pingtest
      async: 3600
      poll: 0
      tags:
        - vpath-create

- hosts: control

  tasks:
    - name: create virtual path
      shell: sleep 4 && /usr/local/bin/snmpd nimbus vlan 2001 set access 3 4 
      async: 3600
      poll: 0
      tags:
        - vpath-create
    
    - name: destroy virtual path
      shell: "{{item}}"
      async: 3600
      poll: 0
      tags:
        - vpath-destroy
      with_items:
        - sleep 7 && /usr/local/bin/snmpd nimbus vlan 2001 clear-all
